:encoding: utf-8

:img-base-url: ../../raw/master/docs/assets

:img-github-fork: {img-base-url}/github-fork.png

:img-heroku-menu: {img-base-url}/heroku-menu.png

:img-heroku-new-dyno: {img-base-url}/heroku-new-dyno.png

:img-heroku-addon-postgres: {img-base-url}/heroku-addon-postgres.png

:img-heroku-addon-search: {img-base-url}/heroku-addon-search.png

:img-heroku-buildpack-gradle: {img-base-url}/heroku-buildpack-gradle.png

:img-heroku-deploy-github: {img-base-url}/heroku-deploy-github.png

:img-heroku-deploy-github-manually: {img-base-url}/heroku-deploy-github-manually.png

= Spring Boot REST SERVER (PgFlyGroGra)

This is a REST server demo project based on Spring Boot with PostgreSQL, Flyway, Groovy and Gradle.

=== How to set up with Heroku

* You need a GitHub account for non critical work and a Heroku account.

* Fork this repository into your account, by following the guide in appendix <<A1,[1]>>. +
TL;DR: Log into your Github account and click on the `Fork` button. +
image:{img-github-fork}[]

* Eventually add this fork to a new Heroku dyno instance by following the guide in appendix <<A2,[2]>>. +
TL;DR: Log into your Heroku account. Click on the `menu` button next to your avatar in the +
upper right corner and then click on `dashboard`.
Click on `Create new app` and follow  + 
the on-screen instructions.
When you are done, heroku will redirect you to the dyno +
overview dashboard. Here you will have to click on `Configure Add-ons` to add the Heroku +
**Postgres Addon** to your project. Now locate the `Settings` tab of your dyno dashboard. +
Click on it and scroll down to locate the `Add buildbpack` button. Use it to add the **Gradle Buildpack**. +
Finally click on the `Deploy` tab of your dyno dashboard and than on `Connect to GitHub`. +
Enter your GitHub repository url, click on `connect`; enter your GitHub credentials and allow +
Heroku to take control over your GitHub repository. Scroll down and click on `Deploy branch`. +
image:{img-heroku-menu}[] +
image:{img-heroku-new-dyno}[] +
image:{img-heroku-addon-postgres}[] +
image:{img-heroku-addon-search}[] +
image:{img-heroku-buildpack-gradle}[] +
image:{img-heroku-deploy-github}[] +
image:{img-heroku-deploy-github-manually}[] +

=== How to use

* Install a browser addon like RESTer <<A3,[3]>> or +
  a standalone app like Advanced REST Client <<A4,[4]>> / Postman <<A5,[5]>>

* On your dyno dashboard click on the `Settings` tab and scroll down to Domains.

* Click on the link after `Your app can be found at` to open the start page of your REST demo server. +
  You should see the message: +
  _This is Groovy land. Keep out of here!_

* Try the same with your REST addon or REST standalone app (aka REST client). +
  Set *METHODE* to *GET* and copy paste the *previous link* into *url field*; hit *enter*. +
  You should see: +
  _Response 200_ +
  _This is Groovy land. Keep out of here!_

* Now append _/tasks_ to the *url input* of your REST client; hit *enter*. +
  You should see: +
   _Response 200_ +
----
[
    {
        "id": 1,
        "title": "Task A",
        "description": "Task A Description"
    },
    {
        "id": 2,
        "title": "Task B",
        "description": "Task B Description"
    }
]
----

* Next append _/1_ or _/2_ to _/tasks_ in the *url input* of your REST client; hit *enter*. +
  You should see: +
   _Response 200_ +
----
{
    "id": 1,
    "title": "Task A",
    "description": "Task A Description"
}
----

* Finally set *METHODE* to *POST* and *url* to _{your server url}/task/add_. +
  Click on `Header` and set *Name* to _Content-Type_ and *Value* to _application/json_ + 
  Click on `Body`. +
  Before you continue with *RESTer* do the following: click in the corresponding text box on the `dotted menu` button and select `Plain` (not `JSON`). +
  Paste into the `Body` text box and hit *enter*: +
----
{
    "title": "Task C",
    "description": "Task C Description"
}
----
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} You should see: +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp} _Response 200_
----
{
    "id": 3,
    "title": "Task C",
    "description": "Task C Description"
}
----



=== Appendix
[[A1]] [1] https://help.github.com/en/github/getting-started-with-github/fork-a-repo +
[[A2]] [2] https://devcenter.heroku.com/articles/github-integration +
[[A3]] [3] https://github.com/frigus02/RESTer +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}https://addons.mozilla.org/firefox/addon/rester +
{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}https://chrome.google.com/webstore/detail/rester/eejfoncpjfgmeleakejdcanedmefagga +
[[A4]] [4] https://install.advancedrestclient.com/install +
[[A5]] [5] https://www.postman.com/ +