:encoding: utf-8

:img-base-url: ../../raw/master/docs/assets

:img-github-fork: {img-base-url}/github-fork.png

:img-heroku-menu: {img-base-url}/heroku-menu.png

:img-heroku-new-dyno: {img-base-url}/heroku-new-dyno.png

:img-heroku-addon-postgres: {img-base-url}/heroku-addon-postgres.png

:img-heroku-addon-search: {img-base-url}/heroku-addon-search.png

:img-heroku-buildpack-gradle: {img-base-url}/heroku-buildpack-gradle.png

:img-heroku-deploy-github: {img-base-url}/heroku-deploy-github.png

:img-heroku-deploy-github-manually: {img-base-url}/heroku-deploy-github-manually.png

= Spring Boot REST SERVER (PgFlyGroGra)

This is a REST server demo project based on Spring Boot with PostgreSQL, Flyway, Groovy and Gradle.

=== How to set up with Heroku

* You need a GitHub account for non critical work and a Heroku account.

* Fork this repository into your account, by following the guide in appendix <<A1,[1]>>. +
TL;DR: Log into your Github account and click on the `Fork` button. +
image:{img-github-fork}[]

* Eventually add this fork to a new Heroku dyno instance by following the guide in appendix <<A2,[2]>>. +
TL;DR: Log into your Heroku account. Click on the `menu` button next to your avatar in the +
upper right corner and then click on `dashboard`.
Click on `Create new app` and follow  + 
the on-screen instructions.
When you are done, heroku will redirect you to the dyno +
overview dashboard. Here you will have to click on `Configure Add-ons` to add the Heroku +
**Postgres Addon** to your project. Now locate the `Settings` tab of your dyno dashboard. +
Click on it and scroll down to locate the `Add buildbpack` button. Use it to add the **Gradle Buildpack**. +
Finally click on the `Deploy` tab of your dyno dashboard and than on `Connect to GitHub`. +
Enter your GitHub repository url, click on `connect`; enter your GitHub credentials and allow +
Heroku to take control over your GitHub repository. Scroll down and click on `Deploy branch`. +
image:{img-heroku-menu}[] +
image:{img-heroku-new-dyno}[] +
image:{img-heroku-addon-postgres}[] +
image:{img-heroku-addon-search}[] +
image:{img-heroku-buildpack-gradle}[] +
image:{img-heroku-deploy-github}[] +
image:{img-heroku-deploy-github-manually}[] +

=== Appendix
[[A1]] [1] https://help.github.com/en/github/getting-started-with-github/fork-a-repo +
[[A2]] [2] https://devcenter.heroku.com/articles/github-integration